---
- name: Download
  hosts: localhost
  gather_facts: False
  tasks: 
   - name: install http
     yum:
       name: httpd
       state: present


   - name: service start
     service: 
        name: httpd
        state: started      
